Repository SSAFY5thSeoul13-Algo/SSAFY5th_13_4_Algo_Study, pull requests merged in 2021-08, with the labels that each got.

#197 DAUN JO : Programmers Lv2 기능개발
  jodawoooon/src/week21/PRG_Lv2_기능개발/README.md
  jodawoooon/src/week21/PRG_Lv2_기능개발/Solution_PRG_Lv2_기능개발.java
Labels: Impl

#202 DAUN JO : Programmers Lv2 프린터
  jodawoooon/src/week21/PRG_Lv2_프린터/README.md
  jodawoooon/src/week21/PRG_Lv2_프린터/Solution_PRG_Lv2_프린터.java
Labels: Hash, Map, Queue

#203 DAUN JO : Programmers Lv2 다리를 지나는 트럭
  jodawoooon/src/week21/PRG_Lv2_다리를지나는트럭/README.md
  jodawoooon/src/week21/PRG_Lv2_다리를지나는트럭/Solution_PRG_Lv2_다리를지나는트럭.java
Labels: Queue

#204 DAUN JO : Programmers Lv2 주식가격
  jodawoooon/src/week21/PRG_Lv2_주식갸격/Programmers_PRG_Lv2_주식가격.java
  jodawoooon/src/week21/PRG_Lv2_주식갸격/README.md
Labels: Impl

#209 DAUN JO : Programmers Lv3 등굣길
  jodawoooon/src/week21/PRG_Lv3_등굣길/README.md
  jodawoooon/src/week21/PRG_Lv3_등굣길/Solution_PRG_Lv3_등굣길.java
Labels: DP

#211 DAUN JO : Programmers Lv4 도둑질
  jodawoooon/src/week21/PRG_Lv4_도둑질/README.md
  jodawoooon/src/week21/PRG_Lv4_도둑질/Solution_PRG_Lv4_도둑질.java
Labels: DP

#219 HYEWON CHOI : BOJ 2805 S3 나무자르기
  choihyewon/src/week22/boj2805/BOJ_2805_S3_나무자르기.java
  choihyewon/src/week22/boj2805/readme.md
Labels: BinarySearch

#220 HYEWON CHOI : BOJ 1654 S3 랜선자르기
  choihyewon/src/week22/boj1654/BOJ_1654_S3_랜선자르기.java
  choihyewon/src/week22/boj1654/readme.md
Labels: BinarySearch

#221 HYEWON CHOI : BOJ 12015 G2 가장 긴 증가하는 부분수열2
  choihyewon/src/week22/boj12015/BOJ_12015_G2_가장_긴_증가하는_부분수열2.java
  choihyewon/src/week22/boj12015/readme.md
Labels: BinarySearch

#230 HYEWON CHOI : BOJ 2110 S1 공유기 설치
  choihyewon/src/week22/boj2110/BOJ_2110_S1_공유기_설치.java
  choihyewon/src/week22/boj2110/readme.md
Labels: BinarySearch

#234 DAUN JO : BOJ 12015 G2 가장 긴 증가하는 부분 수열 2
  jodawoooon/src/week22/BOJ_12015_G2_가장긴증가하는부분수열2/Main_BOJ_12015_G2_가장긴증가하는부분수열2.java
  jodawoooon/src/week22/BOJ_12015_G2_가장긴증가하는부분수열2/README.md
Labels: BinarySearch

#231 DAUN JO : BOJ 2110 S1 공유기 설치
  jodawoooon/src/week22/BOJ_2110_S1_공유기설치/Main_BOJ_2110_S1_공유기설치.java
  jodawoooon/src/week22/BOJ_2110_S1_공유기설치/README.md
Labels: BinarySearch

#226 DAUN JO : BOJ 1654 S3 랜선자르기
  jodawoooon/src/week22/BOJ_1654_S3_랜선자르기/Main_BOJ_1654_S3_랜선자르기.java
  jodawoooon/src/week22/BOJ_1654_S3_랜선자르기/README.md
Labels: BinarySearch

#227 DAUN JO : BOJ 2805 S3 나무자르기
  jodawoooon/src/week22/BOJ_2805_S3_나무자르기/Main_BOJ_2805_S3_나무자르기.java
  jodawoooon/src/week22/BOJ_2805_S3_나무자르기/README.md
Labels: BinarySearch

#224 HYEONMIN JO : BOJ 1654 S3 랜선 자르기
  Hyeonmin/src/week22/BOJ_1654_S3_랜선자르기/BOJ_1654_S3_랜선자르기.java
  Hyeonmin/src/week22/BOJ_1654_S3_랜선자르기/readme.md
Labels: BinarySearch

#225 HYEONMIN JO : BOJ 2805 S3 나무 자르기
  Hyeonmin/src/week22/BOJ_2805_S3_나무자르기/BOJ_2805_S3_나무자르기.java
  Hyeonmin/src/week22/BOJ_2805_S3_나무자르기/readme.md
Labels: BinarySearch

#228 HYEONMIN JO: BOJ 12015 G2 가장 긴 증가하는 부분 수열2
  Hyeonmin/src/week22/BOJ_12015_G2_가장긴증가하는부분수열2/BOJ_12015_G2_가장긴증가하는부분수열2.java
  Hyeonmin/src/week22/BOJ_12015_G2_가장긴증가하는부분수열2/readme.md
Labels: BinarySearch

#229 HYEONMIN JO: BOJ 2110 S1 공유기 설치
  Hyeonmin/src/week22/BOJ_2110_S1_공유기설치/BOJ_2110_S1_공유기설치.java
  Hyeonmin/src/week22/BOJ_2110_S1_공유기설치/readme.md
Labels: BinarySearch

#222 SEONG UK MOON : BOJ 1654 S3 랜선 자르기
  moonganae/src/week22/BOJ_1654_S3_랜선자르기/Main.java
  moonganae/src/week22/BOJ_1654_S3_랜선자르기/readme.md
Labels: BinarySearch

#223 SEONG UK MOON : BOJ 2805 S3 나무 자르기
  moonganae/src/week22/BOJ_2805_S3_나무자르기/Main.java
  moonganae/src/week22/BOJ_2805_S3_나무자르기/readme.md
Labels: BinarySearch

#232 SEONG UK MOON : BOJ 12015 G2 가장 긴 증가하는 부분수열 2
  moonganae/src/week22/BOJ_12015_G2_가장긴증가하는부분수열2/Main.java
  moonganae/src/week22/BOJ_12015_G2_가장긴증가하는부분수열2/readme.md
Labels: BinarySearch

#233 SEONG UK MOON : BOJ 2110 S1 공유기 설치
  moonganae/src/week22/BOJ_2110_S1_공유기설치/Main.java
  moonganae/src/week22/BOJ_2110_S1_공유기설치/readme.md
Labels: BinarySearch

#238 DAUN JO : BOJ 1068 G5 트리
  jodawoooon/src/week23/BOJ_1068_G5_트리/Main_BOJ_1068_G5_트리.java
  jodawoooon/src/week23/BOJ_1068_G5_트리/README.md
Labels: Tree

#242 DAUN JO : BOJ 5639 S1 이진 검색 트리
  jodawoooon/src/week23/BOJ_5639_S1_이진검색트리/Main_BOJ_5639_S1_이진검색트리.java
  jodawoooon/src/week23/BOJ_5639_S1_이진검색트리/README.md
Labels: Tree

#241 HYEONMIN JO: BOJ G4 전화번호 목록
  Hyeonmin/src/week23/BOJ_5052_G4_전화번호목록/BOJ_5052_G4_전화번호목록.java
  Hyeonmin/src/week23/BOJ_5052_G4_전화번호목록/BOJ_5052_G4_전화번호목록_Trie.java
  Hyeonmin/src/week23/BOJ_5052_G4_전화번호목록/readme.md
Labels: Tree, Trie

#240 HYEONMIN JO: BOJ 5639 S1 이진검색트리
  Hyeonmin/src/week23/BOJ_5639_S1_이진검색트리/BOJ_5639_S1_이진검색트리.java
  Hyeonmin/src/week23/BOJ_5639_S1_이진검색트리/readme.md
Labels: Tree

#237 HYEONMIN JO: BOJ 1068 G5 트리
  Hyeonmin/src/week23/BOJ_1068_G5_트리/BOJ_1068_G5_트리.java
  Hyeonmin/src/week23/BOJ_1068_G5_트리/readme.md
Labels: Tree

#244 SEONG UK MOON : BOJ 5639 S1 이진검색트리
  moonganae/src/week23/BOJ_5639_S1_이진검색트리/Main.java
  moonganae/src/week23/BOJ_5639_S1_이진검색트리/readme.md
Labels: Graph

#239 SEONG UK MOON : BOJ 1068 G5 트리
  moonganae/src/week23/BOJ_1068_G5_트리/Main.java
  moonganae/src/week23/BOJ_1068_G5_트리/readme.md
Labels: DFS, Graph

#247 SEONG UK MOON : BOJ 2428 S3 표절
  moonganae/src/week24/BOJ_2428_S3_표절/Main.java
  moonganae/src/week24/BOJ_2428_S3_표절/readme.md
Labels: SlidingWindow, Sorting

#248 SEONG UK MOON : BOJ 2096 G4 내려가기
  moonganae/src/week24/BOJ_2096_G4_내려가기/Main.java
  moonganae/src/week24/BOJ_2096_G4_내려가기/readme.md
Labels: DP

#256 SEONG UK MOON : BOJ 2075 G5 N번째 큰수
  moonganae/src/week24/BOJ_2075_G5_N번째큰수/Main.java
  moonganae/src/week24/BOJ_2075_G5_N번째큰수/readme.md
Labels: Sorting, PriorityQueue

#258 SEONG UK MOON : BOJ 1593 G4 문자해독
  moonganae/src/week24/BOJ_1593_G4_문자해독/Main.java
  moonganae/src/week24/BOJ_1593_G4_문자해독/readme.md
Labels: SlidingWindow
