Repository SSAFY5thSeoul13-Algo/SSAFY5th_13_4_Algo_Study, pull requests merged in 2021-10, with the labels that each got.

#303 SEONG UK MOON : BOJ 2661 G4 좋은수열
  moonganae/src/week28_BOJ_2661_G4_좋은수열/Main.java
  moonganae/src/week28_BOJ_2661_G4_좋은수열/readme.md
Labels: Backtracking

#298 SEONG UK MOON : BOJ 1038 G5 감소하는 수
  moonganae/src/week28_BOJ__1038_G5_감소하는수/Main.java
  moonganae/src/week28_BOJ__1038_G5_감소하는수/readme.md
Labels: Backtracking

#297 SEONG UK MOON : BOJ 11441 S3 합구하기
  moonganae/src/week28_BOJ__11441_S3_합구하기/Main.java
  moonganae/src/week28_BOJ__11441_S3_합구하기/readme.md
Labels: Prefix Sum

#327 DAUN JO : BOJ 2630 S3 색종이만들기
  jodawoooon/src/week29/BOJ_2630_S3_색종이만들기/Main_BOJ_2630_S3_색종이만들기.java
  jodawoooon/src/week29/BOJ_2630_S3_색종이만들기/README.md
Labels: DivideAndConquer

#315 HYEONMIN JO: BOJ 2206 G4 벽 부수고 이동하기
  Hyeonmin/src/week29/BOJ_2206_G4_벽부수고이동하기/BOJ_2206_G4_벽부수고이동하기.java
  Hyeonmin/src/week29/BOJ_2206_G4_벽부수고이동하기/readme.md
Labels: BFS

#311 HYEONMiN JO: BOJ 2630 S3 색종이 만들기
  Hyeonmin/src/week29/BOJ_2630_S3_색종이만들기/BOJ_2630_S3_색종이만들기.java
  Hyeonmin/src/week29/BOJ_2630_S3_색종이만들기/readme.md
Labels: DivideAndConquer

#321 SEONG UK MOON : BOJ 2206 G4 벽 부수고 이동하기
  moonganae/src/week29/BOJ__2206_G4_벽부수고이동하기/Main.java
  moonganae/src/week29/BOJ__2206_G4_벽부수고이동하기/readme.md
Labels: BFS

#344 HYEONMIN JO: BOJ 17837 G2 새로운 게임 2
  Hyeonmin/src/week31/BOJ_17837_G2_새로운게임2/BOJ_17837_G2_새로운게임2.java
  Hyeonmin/src/week31/BOJ_17837_G2_새로운게임2/readme.md
Labels: Simulation, Impl

#343 HYEONMIN JO: BOJ G4 17140 이차원 배열과 연산
  Hyeonmin/src/week31/BOJ_17140_G4_이차원배열과연산/BOJ_17140_G4_이차원배열과연산.java
  Hyeonmin/src/week31/BOJ_17140_G4_이차원배열과연산/readme.md
Labels: Simulation, Sorting

#340 HYEONMIN JO: BOJ 1405 G5 미친 로봇
  Hyeonmin/src/week31/BOJ_1405_G5_미친로봇/BOJ_1405_G5_미친로봇.java
  Hyeonmin/src/week31/BOJ_1405_G5_미친로봇/readme.md
Labels: DFS, Backtracking

#338 HYEONMIN JO: BOJ 7682 G5 틱택토
  Hyeonmin/src/week31/BOJ_7682_G5_틱택토/BOJ_7682_G5_틱택토.java
  Hyeonmin/src/week31/BOJ_7682_G5_틱택토/readme.md
Labels: Simulation, Backtracking
