Repository SSAFY5thSeoul13-Algo/SSAFY5th_13_4_Algo_Study, pull requests merged in 2021-12, with the labels that each got.

#357 HYEWON CHOI : BOJ 17086 S2 아기상어2
  choihyewon/src/week33/boj17086/BOJ_17086_S2_아기상어2.java
  choihyewon/src/week33/boj17086/readme.md
Labels: BFS

#362 HYEONMIN JO : BOJ 18428 S1 감시피하기
  Hyeonmin/src/week33/BOJ_18428_S1_감시피하기/BOJ_18428_S1_감시피하기.java
  Hyeonmin/src/week33/BOJ_18428_S1_감시피하기/readme.md
Labels: Bruteforcing, Backtracking

#363 HYEONMIN JO: BOJ 10159 G3 저울
  Hyeonmin/src/week33/BOJ_10159_G3_저울/BOJ_10159_G3_저울.java
  Hyeonmin/src/week33/BOJ_10159_G3_저울/readme.md
Labels: Floyd–Warshall

#364 HYEONMIN JO : BOJ 4256 G3 트리
  Hyeonmin/src/week33/BOJ_4256_G3_트리/BOJ_4256_G3_트리.java
  Hyeonmin/src/week33/BOJ_4256_G3_트리/readme.md
Labels: Tree, DivideAndConquer

#359 HYEONMIN JO: BOJ 17086 S2 아기상어
  Hyeonmin/src/week33/BOJ_17086_S2_아기상어2/BOJ_17086_S2_아기상어2.java
  Hyeonmin/src/week33/BOJ_17086_S2_아기상어2/readme.md
Labels: BFS
