Repository SSAFY5thSeoul13-Algo/SSAFY5th_13_4_Algo_Study, pull requests merged in 2021-09, with the labels that each got.

#253 DAUN JO : BOJ 2428 S3 표절
  jodawoooon/src/week24/BOJ_2428_S3_표절/Main_BOJ_2428_S3_표절.java
  jodawoooon/src/week24/BOJ_2428_S3_표절/README.md
Labels: TwoPointer

#255 DAUN JO : BOJ 2428 G4 내려가기
  jodawoooon/src/week24/BOJ_2096_G4_내려가기/Main_BOJ_2096_G4_내려가기.java
  jodawoooon/src/week24/BOJ_2096_G4_내려가기/README.md
Labels: DP

#259 DAUN JO : BOJ 2075 G5 N번째 큰 수
  jodawoooon/src/week24/BOJ_2075_G5_N번째큰수/Main_BOJ_2075_G5_N번째큰수.java
  jodawoooon/src/week24/BOJ_2075_G5_N번째큰수/README.md
Labels: SlidingWindow, PriorityQueue

#261 DAUN JO : BOJ 1593 G4 문자 해독
  jodawoooon/src/week24/BOJ_1593_G4_문자해독/Main_BOJ_1593_G4_문자해독.java
  jodawoooon/src/week24/BOJ_1593_G4_문자해독/README.md
Labels: SlidingWindow

#250 HYEONMIN JO: BOJ 1593 G4 문자 해독
  Hyeonmin/src/week24/BOJ_1593_G4_문자해독/BOJ_1593_G4_문자해독.java
  Hyeonmin/src/week24/BOJ_1593_G4_문자해독/readme.md
Labels: SlidingWindow

#246 HYEONMIN JO: BOJ 2096 G4 내려가기
  Hyeonmin/src/week24/BOJ_2096_G4_내려가기/BOJ_2096_G4_내려가기.java
  Hyeonmin/src/week24/BOJ_2096_G4_내려가기/readme.md
Labels: DP

#252 HYEONMIN JO: BOJ 2428 S3 표절
  Hyeonmin/src/week24/BOJ_2428_S3_표절/BOJ_2428_S3_표절.java
  Hyeonmin/src/week24/BOJ_2428_S3_표절/BOJ_2428_S3_표절_풀이2.java
  Hyeonmin/src/week24/BOJ_2428_S3_표절/readme.md
Labels: SlidingWindow, BinarySearch

#257 HYEONMIN JO: BOJ 2075 N번째 큰 수
  Hyeonmin/src/week24/BOJ_2075_G5_N번째큰수/BOJ_2075_G5_N번째큰수.java
  Hyeonmin/src/week24/BOJ_2075_G5_N번째큰수/readme.md
Labels: PriorityQueue

#249 HYEWON CHOI : BOJ 2075 G5 N번째 큰 수
  choihyewon/src/week24/boj2075/BOJ_2075_G5_N번째_큰_수.java
  choihyewon/src/week24/boj2075/readme.md
Labels: SlidingWindow, PriorityQueue

#260 HYEWON CHOI : BOJ 1593 G4 문자해독
  choihyewon/src/week24/boj1593/BOJ_1593_G4_문자해독.java
  choihyewon/src/week24/boj1593/readme.md
Labels: SlidingWindow

#254 HYEWON CHOI : BOJ 2096 G4 내려가기
  choihyewon/src/week24/boj2096/BOJ_2096_G4_내려가기.java
  choihyewon/src/week24/boj2096/readme.md
Labels: DP

#251 HYEWON CHOI : BOJ 2428 S3 표절
  choihyewon/src/week24/boj2428/BOJ_2428_S3_표절.java
  choihyewon/src/week24/boj2428/readme.md
Labels: BinarySearch

#265 HYEWON CHOI : BOJ 1922 G4 네트워크 연결
  choihyewon/src/week25/boj1922/BOJ_1922_G4_네트워크_연결.java
  choihyewon/src/week25/boj1922/readme.md
Labels: Kruskal

#266 HYEWON CHOI : BOJ 1197 G4 최소 스패닝 트리
  choihyewon/src/week25/boj1197/BOJ_1197_G4_최소_스패닝_트리_Kruskal.java
  choihyewon/src/week25/boj1197/BOJ_1197_G4_최소_스패닝_트리_Prim.java
  choihyewon/src/week25/boj1197/readme.md
Labels: Prim, Kruskal

#267 HYEWON CHOI : BOJ 1647 G4 도시 분할 계획
  choihyewon/src/week25/boj1647/BOJ_1647_G4_도시_분할_계획.java
  choihyewon/src/week25/boj1647/readme.md
Labels: Kruskal

#273 HYEWON CHOI : BOJ 16398 G4 행성 연결
  choihyewon/src/week25/boj16398/BOJ_16398_G4_행성_연결.java
  choihyewon/src/week25/boj16398/readme.md
Labels: Kruskal

#262 DAUN JO : BOJ 1197 G4 최소 스패닝 트리
  jodawoooon/src/week25/BOJ_1197_G4_최소스패닝트리/Main_BOJ_1197_G4_최소스패닝트리_크루스칼.java
  jodawoooon/src/week25/BOJ_1197_G4_최소스패닝트리/Main_BOJ_1197_G4_최소스패닝트리_프림.java
  jodawoooon/src/week25/BOJ_1197_G4_최소스패닝트리/README.md
Labels: Prim, Kruskal

#274 DAUN JO : BOJ 1647 G4 도시분할계획
  jodawoooon/src/week25/BOJ_1647_G4_도시분할계획/Main_BOJ_1647_G4_도시분할계획.java
  jodawoooon/src/week25/BOJ_1647_G4_도시분할계획/README.md
Labels: Kruskal

#275 DAUN JO : BOJ 16398 G4 행성연결
  jodawoooon/src/week25/BOJ_16398_G4_행성연결/Main_BOJ_16398_G4_행성연결.java
  jodawoooon/src/week25/BOJ_16398_G4_행성연결/README.md
Labels: Kruskal

#276 DAUN JO : BOJ 1922 G4 네트워크연결
  jodawoooon/src/week25/BOJ_1922_G4_네트워크연결/Main_BOJ_1922_G4_네트워크연결.java
  jodawoooon/src/week25/BOJ_1922_G4_네트워크연결/README.md
Labels: Kruskal

#272 HYEONMIN JO: BOJ 1647 G4 도시 분할 계획
  Hyeonmin/src/week25/BOJ_1647_도시분할계획/BOJ_1647_도시분할계획_kruskal.java
  Hyeonmin/src/week25/BOJ_1647_도시분할계획/BOJ_1647_도시분할계획_prim.java
  Hyeonmin/src/week25/BOJ_1647_도시분할계획/readme.md
Labels: Prim, Kruskal

#271 HYEONMIN JO: BOJ 1922 G4 네트워크 연결
  Hyeonmin/src/week25/BOJ_1922_G4_네트워크연결/BOJ_1922_G4_네트워크연결.java
  Hyeonmin/src/week25/BOJ_1922_G4_네트워크연결/readme.md
Labels: Prim

#264 HYEONMIN JO: BOJ 16398 G4 행성 연결
  Hyeonmin/src/week25/BOJ_16398_G4_행성연결/BOJ_16398_G4_행성연결.java
  Hyeonmin/src/week25/BOJ_16398_G4_행성연결/readme.md
Labels: Kruskal

#263 HYEONMIN JO: BOJ 1197 G4 최소 스패닝 트리
  Hyeonmin/src/week25/BOJ_1197_G4_최소스패닝트리/BOJ_1197_G4_최소스패닝트리.java
  Hyeonmin/src/week25/BOJ_1197_G4_최소스패닝트리/readme.md
Labels: Prim

#284 HYEONMIN JO: Programmers 경주로 건설
  Hyeonmin/src/week26/Programmers_경주로건설/Programmers_경주로건설.java
  Hyeonmin/src/week26/Programmers_경주로건설/readme.md
Labels: BFS

#286 HYEWON CHOI : PROGRAMMERS LV3 합승택시요금
  choihyewon/src/week26/programmers합승택시요금/PROGRAMMERS_합승택시요금.java
  choihyewon/src/week26/programmers합승택시요금/readme.md
Labels: Dijkstra

#281 HYEWON CHOI : PROGRAMMERS LV3 경주로 건설
  choihyewon/src/week26/Programmers경주로건설/PROGRAMMERS_경주로_건설.java
  choihyewon/src/week26/Programmers경주로건설/readme.md
Labels: BFS

#279 HYEWON CHOI : PROGRAMMERS LV2 배달
  choihyewon/src/week26/programmers배달/PROGRAMMERS_배달.java
  choihyewon/src/week26/programmers배달/readme.md
Labels: Dijkstra

#278 HYEWON CHOI : BOJ 1504 G4 특정한 최단경로
  choihyewon/src/week26/boj1504/BOJ_1504_G4_특정한_최단경로.java
  choihyewon/src/week26/boj1504/readme.md
Labels: Dijkstra

#282 DAUN JO : Programmers Lv3 합승 택시 요금
  jodawoooon/src/week26/PRG_Lv3_합승택시요금/README.md
  jodawoooon/src/week26/PRG_Lv3_합승택시요금/Solution_PRG_Lv3_합승택시요금.java
Labels: Floyd–Warshall

#287 DAUN JO : BOJ 1504 G4 특정한 최단경로
  jodawoooon/src/week26/BOJ_1504_G4_특정한최단경로/Main_BOJ_1504_G4_특정한최단경로.java
  jodawoooon/src/week26/BOJ_1504_G4_특정한최단경로/README.md
Labels: Dijkstra

#288 DAUN JO : Programmers Lv2 배달
  jodawoooon/src/week26/PRG_Lv2_배달/README.md
  jodawoooon/src/week26/PRG_Lv2_배달/Solution_PRG_Lv2_배달.java
Labels: Dijkstra

#285 HYEONMIN JO: Programmers 경주로 건설
  Hyeonmin/src/week26/Programmers_경주로건설/Programmers_경주로건설.java
  Hyeonmin/src/week26/Programmers_경주로건설/readme.md
Labels: BFS

#283 HYEONMIN JO: Programmers 배달
  Hyeonmin/src/week26/Programmers_배달/Programmers_배달.java
  Hyeonmin/src/week26/Programmers_배달/readme.md
Labels: Dijkstra

#280 HYEONMIN JO: Programmers 합승 택시 요금
  Hyeonmin/src/week26/Programmers_합승택시요금/Programmers_합승택시요금.java
  Hyeonmin/src/week26/Programmers_합승택시요금/readme.md
Labels: Dijkstra

#277 HYEONMIN JO: BOJ 1504 G4 특정한 최단 경로
  Hyeonmin/src/week26/BOJ_1504_G4_특정한최단경로/BOJ_1504_G4_특정한최단경로.java
  Hyeonmin/src/week26/BOJ_1504_G4_특정한최단경로/readme.md
Labels: Dijkstra

#289 HYEWON CHOI : BOJ 3190 G5 뱀
  choihyewon/src/week27/boj3190/BOJ_3190_G5_뱀.java
  choihyewon/src/week27/boj3190/readme.md
Labels: Simulation

#296 HYEWON CHOI : BOJ 21610 G5 마법사 상어와 비바라기
  choihyewon/src/week27/boj21610/BOJ_21610_G5_마법사_상어와_비바라기.java
  choihyewon/src/week27/boj21610/readme.md
Labels: Simulation

#293 DAUN JO : BOJ 21610 G5 마법사 상어와 비바라기
  jodawoooon/src/week27/BOJ_21610_G5_마법사상어와비바라기/Main_BOJ_21610_G5_마법사상어와비바라기.java
  jodawoooon/src/week27/BOJ_21610_G5_마법사상어와비바라기/README.md
Labels: Simulation

#295 DAUN JO : BOJ 3190 G5 뱀
  jodawoooon/src/week27/BOJ_3190_G5_뱀/Main_BOJ_3190_G5_뱀.java
  jodawoooon/src/week27/BOJ_3190_G5_뱀/README.md
Labels: Simulation

#294 HYEONMIN JO: BOJ 1938 G2 통나무 옮기기
  Hyeonmin/src/week27/BOJ_1938_G2_통나무옮기기/BOJ_1938_G2_통나무옮기기.java
  Hyeonmin/src/week27/BOJ_1938_G2_통나무옮기기/readme.md
Labels: BFS, Simulation

#292 HYEONMIN JO: BOJ 17779 G4 게리맨더링2
  Hyeonmin/src/week27/BOJ_17779_G4_개리맨더링2/BOJ_17779_G4_개리맨더링2.java
  Hyeonmin/src/week27/BOJ_17779_G4_개리맨더링2/readme.md
Labels: Simulation

#291 HYEONMIN JO: BOJ 21610 G5 마법사 상어와 비바라기
  Hyeonmin/src/week27/BOJ_21610_G5_마법사상어와비바라기/BOJ_21610_G5_마법사상어와비바라기.java
  Hyeonmin/src/week27/BOJ_21610_G5_마법사상어와비바라기/readme.md
Labels: Simulation

#290 HYEONMIN JO: BOJ 3190 G5 뱀
  Hyeonmin/src/week27/BOJ_3190_G5_뱀/BOJ_3190_G5_뱀.java
  Hyeonmin/src/week27/BOJ_3190_G5_뱀/readme.md
Labels: Simulation, Queue, deque

#301 DAUN JO : BOJ 11441 S3 합 구하기
  jodawoooon/src/week28/BOJ_11441_S3_합구하기/Main_BOJ_11441_S3_합구하기.java
  jodawoooon/src/week28/BOJ_11441_S3_합구하기/README.md
Labels: Prefix Sum

#307 DAUN JO : BOJ 1038 G5 감소하는 수
  jodawoooon/src/week28/BOJ_1038_G5_감소하는수/Main_BOJ_1038_G5_감소하는수.java
  jodawoooon/src/week28/BOJ_1038_G5_감소하는수/README.md
Labels: Backtracking

#310 DAUN JO : BOJ 10986 G3 나머지 합
  jodawoooon/src/week28/BOJ_10986_G3_나머지합/Main_BOJ_10986_G3_나머지합.java
  jodawoooon/src/week28/BOJ_10986_G3_나머지합/README.md
Labels: Prefix Sum

#299 HYEWON CHOI : BOJ 11441 S3 합 구하기
  choihyewon/src/week28/boj_11441/BOJ_11441_S3_합_구하기.java
  choihyewon/src/week28/boj_11441/readme.md
Labels: Prefix Sum

#300 HYEWON CHOI : BOJ 10986 G3 나머지 합
  choihyewon/src/week28/boj10986/BOJ_10986_G3_나머지_합.java
  choihyewon/src/week28/boj10986/readme.md
Labels: Math, Prefix Sum

#308 HYEWON CHOI : BOJ 2661 G4 좋은수열
  choihyewon/src/week28/boj2661/BOJ_2661_G4_좋은수열.java
  choihyewon/src/week28/boj2661/readme.md
Labels: Backtracking

#309 HYEONMIN JO: BOJ 2661 G4 좋은수열
  Hyeonmin/src/week28/BOJ_2661_G4_좋은수열/BOJ_2661_G4_좋은수열.java
  Hyeonmin/src/week28/BOJ_2661_G4_좋은수열/readme.md
Labels: Backtracking

#306 HYEONMIN JO: BOJ 1038 G5 감소하는 수
  Hyeonmin/src/week28/BOJ_1038_G5_감소하는수/BOJ_1038_G5_감소하는수.java
  Hyeonmin/src/week28/BOJ_1038_G5_감소하는수/readme.md
Labels: Backtracking

#304 HYEONMIN JO: BOJ 10986 G3 나머지 합
  Hyeonmin/src/week28/BOJ_10986_G3_나머지합/BOJ_10986_G3_나머지합.java
  Hyeonmin/src/week28/BOJ_10986_G3_나머지합/readme.md
Labels: Math, Prefix Sum

#302 HYEONMIN JO: BOJ 11441 S3 합 구하기
  Hyeonmin/src/week28/BOJ_11441_S3_합구하기/BOJ_11441_S3_합구하기.java
  Hyeonmin/src/week28/BOJ_11441_S3_합구하기/readme.md
Labels: Prefix Sum
