Repository SSAFY5thSeoul13-Algo/SSAFY5th_13_4_Algo_Study, pull requests merged in 2021-07, with the labels that each got.

#110 SEONG UK MOON : PROGRAMMERS LV2 소수 찾기
  moonganae/src/week17/PROGRAMMERS_LV2_소수찾기/Solution.java
  moonganae/src/week17/PROGRAMMERS_LV2_소수찾기/readme.md
Labels: Bruteforcing, Set

#111 SEONG UK MOON : PROGRAMMERS LV2 카펫
  moonganae/src/week17/PROGRAMMERS_LV2_카펫/Solution.java
  moonganae/src/week17/PROGRAMMERS_LV2_카펫/carpet.jpeg
  moonganae/src/week17/PROGRAMMERS_LV2_카펫/readme.md
Labels: Math

#113 SEONG UK MOON : PROGRAMMERS LV1 모의고사
  moonganae/src/week17/PROGRAMMERS_LV1_모의고사/Solution.java
  moonganae/src/week17/PROGRAMMERS_LV1_모의고사/readme.md
Labels: Bruteforcing

#120 SEONG UK MOON : PROGRAMMERS LV1 K번째 수
  moonganae/src/week17/PROGRAMMERS_LV1_K번째수/Solution.java
  moonganae/src/week17/PROGRAMMERS_LV1_K번째수/readme.md
Labels: Sorting

#125 SEONG UK MOON : PROGRAMMERS LV2 h-index
  moonganae/src/week17/PROGRAMMERS_LV2_hIndex/Solution.java
  moonganae/src/week17/PROGRAMMERS_LV2_hIndex/readme.md
Labels: Sorting

#126 SEONG UK MOON : PROGRAMMERS LV2 가장큰수
  moonganae/src/week17/PROGRAMMERS_LV2_가장큰수/Solution.java
  moonganae/src/week17/PROGRAMMERS_LV2_가장큰수/readme.md
Labels: Sorting, String

#127 HYEONMIN JO : PROGRAMMERS LV2 타겟 넘버
  Hyeonmin/src/week18/Programmers_LV2_타겟넘버/Programmers_LV2_타겟넘버.java
  Hyeonmin/src/week18/Programmers_LV2_타겟넘버/readme.md
Labels: DFS

#131 DAUN JO : PROGRAMMERS Lv2 타겟넘버
  jodawoooon/src/week18/PRG_Lv2_타겟넘버/README.md
  jodawoooon/src/week18/PRG_Lv2_타겟넘버/Solution_PRG_Lv2_타겟넘버.java
Labels: DFS

#135 DAUN JO : Programmers Lv3 네트워크
  jodawoooon/src/week18/PRG_Lv3_네트워크/README.md
  jodawoooon/src/week18/PRG_Lv3_네트워크/Solution_PRG_Lv3_네트워크.java
Labels: DFS

#137 DAUN JO : Programmers Lv3 단어변환
  jodawoooon/src/week18/PRG_LV3_단어변환/README.md
  jodawoooon/src/week18/PRG_LV3_단어변환/Solution_PRG_LV3_단어변환.java
Labels: BFS

#144 DAUN JO : Programmers Lv3 입국심사
  jodawoooon/src/week18/PRG_Lv3_입국심사/README.md
  jodawoooon/src/week18/PRG_Lv3_입국심사/Solution_PRG_Lv3_입국심사.java
Labels: BinarySearch

#145 DAUN JO : Programmers Lv3 여행경로
  jodawoooon/src/week18/PRG_Lv3_여행경로/README.md
  jodawoooon/src/week18/PRG_Lv3_여행경로/Solution_PRG_Lv3_여행경로.java
Labels: DFS

#128 HYEWON CHOI : PROGRAMMERS LV3 네트워크
  choihyewon/src/week18/dfs_bfs2/readme.md
  choihyewon/src/week18/dfs_bfs2/네트워크.java
Labels: DFS

#129 HYEWON CHOI : PROGRAMMERS LV2 타겟넘버
  choihyewon/src/week18/dfs_bfs1/readme.md
  choihyewon/src/week18/dfs_bfs1/타겟_넘버.java
Labels: DFS

#132 HYEWON CHOI : PROGRAMMERS LV3 단어변환
  choihyewon/src/week18/dfs_bfs3/readme.md
  choihyewon/src/week18/dfs_bfs3/단어변환.java
Labels: Backtracking, DFS

#133 HYEWON CHOI : PROGRAMMERS LV3 여행경로
  choihyewon/src/week18/dfs_bfs4/readme.md
  choihyewon/src/week18/dfs_bfs4/여행경로.java
Labels: Backtracking, DFS

#146 HYEWON CHOI : PROGRAMMERS LV3 입국심사
  choihyewon/src/week18/binarysearch/readme.md
  choihyewon/src/week18/binarysearch/입국심사.java
Labels: BinarySearch

#138 SEONG UK MOON : PROGRAMMERS 타겟 넘버
  moonganae/src/week18/PROGRAMMERS_LV2_타겟넘버/Solution.java
  moonganae/src/week18/PROGRAMMERS_LV2_타겟넘버/readme.md
Labels: DFS

#139 SEONG UK MOON : PROGRAMMERS LV2 네트워크
  moonganae/src/week18/PROGRAMMERS_LV3_네트워크/Solution.java
  moonganae/src/week18/PROGRAMMERS_LV3_네트워크/readme.md
Labels: Union&Find

#140 SEONG UK MOON : PROGRAMMERS LV3 단어변환
  moonganae/src/week18/PROGRAMMERS_LV3_단어변환/Solution.java
  moonganae/src/week18/PROGRAMMERS_LV3_단어변환/readme.md
Labels: DFS

#142 SEONG UK MOON : PROGRAMMERS LV3 여행경로
  moonganae/src/week18/PROGRAMMERS_LV3_여행경로/Solution.java
  moonganae/src/week18/PROGRAMMERS_LV3_여행경로/readme.md
Labels: DFS

#143 SEONG UK MOON : PROGRAMMERS LV3 입국심사
  moonganae/src/week18/PROGRAMMERS_LV3_입국심사/Solution.java
  moonganae/src/week18/PROGRAMMERS_LV3_입국심사/readme.md
Labels: BinarySearch

#149 HYEWON CHOI : PROGRAMMERS LV3 디스크 컨트롤러
  choihyewon/src/week19/heap2/readme.md
  choihyewon/src/week19/heap2/디스크_컨트롤러.java
Labels: PriorityQueue, heap

#158 HYEWON CHOI : PROGRAMMERS LV3 순위
  choihyewon/src/week19/graph2/readme.md
  choihyewon/src/week19/graph2/순위.java
Labels: Floyd–Warshall, Graph

#156 HYEWON CHOI : PROGRAMMERS LV3 가장 먼 노드
  choihyewon/src/week19/graph1/readme.md
  choihyewon/src/week19/graph1/가장_먼_노드.java
Labels: BFS

#151 DAUN JO : Programmers Lv3 가장 먼 노드
  jodawoooon/src/week19/PRG_Lv3_가장먼노드/README.md
  jodawoooon/src/week19/PRG_Lv3_가장먼노드/Solution_PRG_Lv3_가장먼노드.java
Labels: BFS, Graph

#162 DAUN JO : Programmers Lv3 순위
  jodawoooon/src/week19/PRG_Lv3_순위/README.md
  jodawoooon/src/week19/PRG_Lv3_순위/Solution_PRG_Lv3_순위.java
Labels: BFS, Graph

#163 DAUN JO : Programmers Lv2 더 맵게
  jodawoooon/src/week19/PRG_Lv2_더맵게/README.md
  jodawoooon/src/week19/PRG_Lv2_더맵게/Solution_PRG_Lv2_더맵게.java
Labels: PriorityQueue, heap

#164 DAUN JO : Programmers Lv3 디스크 컨트롤러
  jodawoooon/src/week19/PRG_Lv3_디스크컨트롤러/README.md
  jodawoooon/src/week19/PRG_Lv3_디스크컨트롤러/Solution_PRG_Lv3_디스크컨트롤러.java
Labels: PriorityQueue, heap

#165 DAUN JO : Programmers Lv3 이중우선순위큐
  jodawoooon/src/week19/PRG_Lv3_이중우선순위큐/README.md
  jodawoooon/src/week19/PRG_Lv3_이중우선순위큐/Solution_PRG_Lv3_이중우선순위큐.java
  jodawoooon/src/week19/PRG_Lv3_이중우선순위큐/Solution_PRG_Lv3_이중우선순위큐TreeMap.java
Labels: PriorityQueue, heap

#154 SEONG UK MOON : PROGRAMMERS LV3 가장 먼 노드
  moonganae/src/week19/PROGRAMMERS_LV3_가장먼노드/Solution.java
  moonganae/src/week19/PROGRAMMERS_LV3_가장먼노드/readme.md
Labels: BFS, Graph

#157 SEONG UK MOON : PROGRAMMERS LV2 더 맵게
  moonganae/src/week19/PROGRAMMERS_LV2_더맵게/Solution.java
  moonganae/src/week19/PROGRAMMERS_LV2_더맵게/readme.md
Labels: PriorityQueue, heap

#160 SEONG UK MOON : PROGRAMMERS 디스크 컨트롤러
  moonganae/src/week19/PROGRAMMERS_LV3_디스크컨트롤러/Solution.java
  moonganae/src/week19/PROGRAMMERS_LV3_디스크컨트롤러/readme.md
Labels: PriorityQueue

#161 SEONG UK MOON : PROGRAMMERS LV3 이중우선순위큐
  moonganae/src/week19/PROGRAMMERS_LV3_이중우선순위큐/Solution.java
  moonganae/src/week19/PROGRAMMERS_LV3_이중우선순위큐/readme.md
Labels: PriorityQueue

#168 SEONG UK MOON : PROGRAMMERS LV5 방의 개수
  moonganae/src/week19/PROGRAMMERS_LV5_방의개수/Solution.java
  moonganae/src/week19/PROGRAMMERS_LV5_방의개수/readme.md
Labels: Hash, Set

#152 HYEWON CHOI : PROGRAMMERS LV3 이중우선순위큐
  choihyewon/src/week19/heap3/readme.md
  choihyewon/src/week19/heap3/이중_우선순위_큐.java
Labels: PriorityQueue, heap

#147 HYEONMIN JO : PROGRAMMERS LV3 가장 먼 노드
  Hyeonmin/src/week19/Programmers_LV3_가장먼노드/Programmers_LV3_가장먼노드.java
  Hyeonmin/src/week19/Programmers_LV3_가장먼노드/readme.md
Labels: BFS, Graph

#150 HYEONMIN JO : PROGRAMMERS LV3 순위
  Hyeonmin/src/week19/Programmers_LV3_순위/Programmers_LV3_순위.java
  Hyeonmin/src/week19/Programmers_LV3_순위/readme.md
Labels: DFS, Graph

#153 HYEONMIN JO : PROGRAMMERS LV2 더 맵게
  Hyeonmin/src/week19/Programmers_LV2_더맵게/Programmers_LV2_더맵게.java
  Hyeonmin/src/week19/Programmers_LV2_더맵게/readme.md
Labels: PriorityQueue, heap

#159 HYEONMIN JO : Programmers LV3 디스크 컨트롤러
  Hyeonmin/src/week19/Programmers_LV3_디스크컨트롤러/Programmers_LV3_디스크컨트롤러.java
  Hyeonmin/src/week19/Programmers_LV3_디스크컨트롤러/readme.md
Labels: PriorityQueue, heap

#166 HYEONMIN JO : PROGRAMMERS LV3 이중우선순위큐
  Hyeonmin/src/week19/Programmers_LV3_이중우선순위큐/Programmers_LV3_이중우선순위큐.java
  Hyeonmin/src/week19/Programmers_LV3_이중우선순위큐/readme.md
Labels: PriorityQueue, heap

#167 HYEONMIN JO : Programmers LV5 방의 개수
  Hyeonmin/src/week19/Programmers_LV5_방의개수/Programmers_LV5_방의개수.java
  Hyeonmin/src/week19/Programmers_LV5_방의개수/readme.md
Labels: Graph

#155 SEONG UK MOON : PROGRAMMERS LV3 순위
  moonganae/src/week19/PROGRAMMERS_LV3_순위/Solution.java
  moonganae/src/week19/PROGRAMMERS_LV3_순위/readme.md
Labels: Floyd–Warshall, Graph

#184 HYEWON CHOI : PROGRAMMERS LV1 완주하지 못한 선수
  choihyewon/src/week20/hash1/Programmers_완주하지_못한_선수.java
  choihyewon/src/week20/hash1/readme.md
Labels: Hash, Map

#192 HYEWON CHOI : PROGRAMMERS LV3 정수삼각형
  choihyewon/src/week20/dp2/Programmers_정수_삼각형.java
  choihyewon/src/week20/dp2/readme.md
  choihyewon/src/week20/hash1/Programmers_완주하지_못한_선수.java
  choihyewon/src/week20/hash1/readme.md
Labels: DP

#181 HYEWON CHOI : PROGRAMMERS LV3 베스트앨범
  choihyewon/src/week20/hash4/Programmers_베스트앨범.java
  choihyewon/src/week20/hash4/readme.md
Labels: Hash, Map

#174 HYEWON CHOI : PROGRAMMERS LV3 N으로 표현
  choihyewon/src/week20/dp1/programmers_N으로_표현.java
  choihyewon/src/week20/dp1/readme.md
Labels: DFS

#176 HYEWON CHOI : PROGRAMMERS LV2 전화번호 목록
  choihyewon/src/week20/hash2/Programmers_전화번호_목록.java
  choihyewon/src/week20/hash2/readme.md
Labels: array

#177 HYEWON CHOI : PROGRAMMERS LV2 위장
  choihyewon/src/week20/hash3/Programmers_위장.java
  choihyewon/src/week20/hash3/readme.md
Labels: Hash, Map

#172 DAUN JO : Programmers Lv1 완주하지 못한 선수
  jodawoooon/src/week20/PRG_Lv1_완주하지못한선수/README.md
  jodawoooon/src/week20/PRG_Lv1_완주하지못한선수/Solution_PRG_Lv1_완주하지못한선수.java
Labels: Hash, Map

#183 DAUN JO : Programmers Lv2 위장
  jodawoooon/src/week20/PRG_Lv2_위장/README.md
  jodawoooon/src/week20/PRG_Lv2_위장/Solution_PRG_Lv2_위장.java
Labels: Hash, Map

#186 DAUN JO : Programmers Lv3 베스트앨범
  jodawoooon/src/week20/PRG_Lv3_베스트앨범/README.md
  jodawoooon/src/week20/PRG_Lv3_베스트앨범/Solution_PRG_Lv3_베스트앨범.java
Labels: DataStructure, Hash

#173 HYEONMIN JO : Programmers LV2 위장
  Hyeonmin/src/week20/Programmers_LV2_위장/Programmers_LV2_위장.java
  Hyeonmin/src/week20/Programmers_LV2_위장/readme.md
Labels: Hash

#175 HYEONMIN JO : Programmers LV3 베스트앨범
  Hyeonmin/src/week20/Programmers_LV3_베스트앨범/Programmers_LV3_베스트앨범.java
  Hyeonmin/src/week20/Programmers_LV3_베스트앨범/readme.md
Labels: Map, PriorityQueue, Queue

#178 HYEONMIN JO : Programmers LV3 N으로 표현
  Hyeonmin/src/week20/Programmers_LV3_N으로표현/Programmers_LV3_N으로표현.java
  Hyeonmin/src/week20/Programmers_LV3_N으로표현/readme.md
Labels: DP, Set

#171 HYEONMIN JO : Programmers LV2 전화번호 목록
  Hyeonmin/src/week20/Programmers_LV2_전화번호목록/Programmers_LV2_전화번호목록.java
  Hyeonmin/src/week20/Programmers_LV2_전화번호목록/readme.md
Labels: Hash

#170 HYEONMIN JO : Programmers LV1 완주하지 못한 선수
  Hyeonmin/src/week20/Programmers_LV1_완주하지못한선수/Programmers_LV1_완주하지못한선수.java
  Hyeonmin/src/week20/Programmers_LV1_완주하지못한선수/readme.md
Labels: Hash

#182 HYEONMIN JO : Programmers LV3 정수 삼각형
  Hyeonmin/src/week20/Programmers_LV3_정수삼각형/Programmers_LV3_정수삼각형.java
  Hyeonmin/src/week20/Programmers_LV3_정수삼각형/readme.md
Labels: DP

#187 DAUN JO : Programmers Lv2 전화번호 목록
  jodawoooon/src/week20/PRG_Lv2_전화번호목록/README.md
  jodawoooon/src/week20/PRG_Lv2_전화번호목록/Solution_PRG_Lv2_전화번호목록.java
Labels: array

#189 DAUN JO : Programmers Lv3 N으로 표현
  jodawoooon/src/week20/PRG_Lv3_N으로표현/Solution_PRG_Lv3_N으로표현.java
  jodawoooon/src/week20/README.md
Labels: DFS

#190 DAUN JO : Programmers Lv3 정수 삼각형
  jodawoooon/src/week20/PRG_Lv3_정수삼각형/README.md
  jodawoooon/src/week20/PRG_Lv3_정수삼각형/Solution_PRG_Lv3_정수삼각형.java
Labels: DP

#179 SEONG UK MOON : PROGRAMMERS LV1 완주하지 못한 선수
  moonganae/src/week20/PROGRAMMERS_LV1_완주하지못한선수/Solution.java
  moonganae/src/week20/PROGRAMMERS_LV1_완주하지못한선수/readme.md
Labels: Hash, Map

#180 SEONG UK MOON : PROGRAMMERS LV2 위장
  moonganae/src/week20/PROGRAMMERS_LV2_위장/Solution.java
  moonganae/src/week20/PROGRAMMERS_LV2_위장/readme.md
Labels: Hash, Map

#188 SEONG UK MOON : PROGRAMMERS LV3 베스트앨범
  moonganae/src/week20/PROGRAMMERS_LV3_베스트앨범/Solution.java
  moonganae/src/week20/PROGRAMMERS_LV3_베스트앨범/readme.md
Labels: Hash, Map, Sorting

#191 SEONG UK MOON : PROGRAMMERS LV3 N으로 표현
  moonganae/src/week20/PROGRAMMERS_LV3_N으로표현/Solution.java
  moonganae/src/week20/PROGRAMMERS_LV3_N으로표현/readme.md
Labels: DP, Hash, Set

#210 HYEONMIN JO: Programmers LV4 도둑질
  Hyeonmin/src/week21/Programmers_LV4_도둑질/Programmers_LV4_도둑질.java
  Hyeonmin/src/week21/Programmers_LV4_도둑질/readme.md
Labels: DP

#206 HYEONMIN JO : Programmers LV3 등굣길
  Hyeonmin/src/week21/Programmers_LV3_등굣길/Programmers_LV3_등굣길.java
  Hyeonmin/src/week21/Programmers_LV3_등굣길/readme.md
Labels: DP

#201 HYEONMIN JO : Programmers LV2 주식가격
  Hyeonmin/src/week21/Programmers_LV2_주식가격/Programmers_LV2_주식가격.java
  Hyeonmin/src/week21/Programmers_LV2_주식가격/readme.md
Labels: PriorityQueue

#196 HYEONMIN JO : Programmers LV2 다리를 지나는 트럭
  Hyeonmin/src/week21/Programmers_LV2_다리를지나는트럭/Programmers_LV2_다리를지나는트럭.java
  Hyeonmin/src/week21/Programmers_LV2_다리를지나는트럭/readme.md
Labels: Queue

#194 HYEONMIN JO : Programmers LV2 프린터
  Hyeonmin/src/week21/Programmers_LV2_프린터/Programmers_LV2_프린터.java
  Hyeonmin/src/week21/Programmers_LV2_프린터/readme.md
Labels: PriorityQueue, Queue

#200 HYEWON CHOI : PROGRAMMERS LV2 다리를 지나는 트럭
  choihyewon/src/week21/stack_queue3/Programmers_다리를_지나는_트럭.java
  choihyewon/src/week21/stack_queue3/readme.md
Labels: Queue

#198 HYEWON CHOI : PROGRAMMERS LV2 기능개발
  choihyewon/src/week21/stack_queue1/Programmers_기능개발.java
  choihyewon/src/week21/stack_queue1/readme.md
Labels: Queue

#199 HYEWON CHOI : PROGRAMMERS LV2 프린터
  choihyewon/src/week21/stack_queue2/Programmers_프린터.java
  choihyewon/src/week21/stack_queue2/readme.md
Labels: PriorityQueue, Queue

#212 HYEWON CHOI : PROGRAMMERS LV2 주식가격
  choihyewon/src/week21/stack_queue4/Programmers_주식가격.java
  choihyewon/src/week21/stack_queue4/readme.md
Labels: Queue

#205 HYEWON CHOI : PROGRAMMERS LV3 등굣길
  choihyewon/src/week21/dp1/Programmers_등굣길.java
  choihyewon/src/week21/dp1/readme.md
Labels: DP

#216 HYEWON CHOI : PROGRAMMERS LV4 도둑질
  choihyewon/src/week21/dp4/Programmers_도둑질.java
  choihyewon/src/week21/dp4/readme.md
Labels: DP

#217 SEONG UK MOON : PROGRAMMERS LV4 도둑질
  moonganae/src/week21/PROGRAMMERS_LV4_도둑질/Solution.java
  moonganae/src/week21/PROGRAMMERS_LV4_도둑질/readme.md
Labels: DP

#208 SEONG UK MOON : PROGRAMMERS LV2 프린터
  moonganae/src/week21/PROGRAMMERS_LV2_프린터/Solution.java
  moonganae/src/week21/PROGRAMMERS_LV2_프린터/readme.md
Labels: PriorityQueue, Queue

#213 SEONG UK MOON : PROGRAMMERS LV2 다리를 지나는 트럭
  moonganae/src/week21/PROGRAMMERS_LV2_다리를지나는트럭/Solution.java
  moonganae/src/week21/PROGRAMMERS_LV2_다리를지나는트럭/readme.md
Labels: Queue

#214 SEONG UK MOON : PROGRAMMERS LV2 주식가격
  moonganae/src/week21/PROGRAMMERS_LV2_주식가격/Solution.java
  moonganae/src/week21/PROGRAMMERS_LV2_주식가격/readme.md
Labels: Queue

#215 SEONG UK MOON : PROGRAMMERS LV3 등굣길
  moonganae/src/week21/PROGRAMMERS_LV3_등굣길/Solution.java
  moonganae/src/week21/PROGRAMMERS_LV3_등굣길/readme.md
Labels: DP
