Repository SSAFY5thSeoul13-Algo/SSAFY5th_13_4_Algo_Study, pull requests merged in 2021-11, with the labels that each got.

#345 HYEWON : BOJ 9663 G5 N-Queen
  choihyewon/src/week32/boj9663/BOJ_9663_G5_N_Queen.java
  choihyewon/src/week32/boj9663/readme.md
Labels: Backtracking

#346 HYEWON CHOI : BOJ 1956 G4 운동
  choihyewon/src/week32/boj1956/BOJ_1956_G4_운동.java
  choihyewon/src/week32/boj1956/readme.md
Labels: Floyd–Warshall

#347 HYEWON CHOI : BOJ 19236 G2 청소년상어
  choihyewon/src/week32/boj19236/BOJ_19236_G2_청소년상어.java
  choihyewon/src/week32/boj19236/readme.md
Labels: Simulation, Backtracking

#353 HYEWON CHOI : BOJ 2610 G2 회의준비
  choihyewon/src/week32/boj2610/BOJ_2610_G2_회의준비.java
  choihyewon/src/week32/boj2610/readme.md
Labels: Graph, Floyd–Warshall

#349 SEONG UK MOON : BOJ 2610 G2 회의준비
  moonganae/src/week32/BOJ_2610_G2_회의준비/Main.java
  moonganae/src/week32/BOJ_2610_G2_회의준비/readme.md
Labels: Floyd–Warshall, Union&Find

#352 SEONG UK MOON : BOJ 1956 G4 운동
  moonganae/src/week32/BOJ_1956_G4_운동/Main.java
  moonganae/src/week32/BOJ_1956_G4_운동/readme.md
Labels: Floyd–Warshall

#355 SEONG UK MOON : BOJ 9663 G5 N-Queen
  moonganae/src/week32/BOJ_9663_G5_NQueen/Main.java
  moonganae/src/week32/BOJ_9663_G5_NQueen/readme.md
Labels: DFS, Backtracking

#356 SEONG UK MOON : BOJ 19236 G2 청소년 상어
  moonganae/src/week32/BOJ_19236_G2_청소년상어/Main.java
  moonganae/src/week32/BOJ_19236_G2_청소년상어/readme.md
Labels: Simulation, Impl, DFS, Backtracking

#348 HYEONMIN JO: BOJ 9663 G5 N-Queen
  Hyeonmin/src/week32/BOJ_9663_G5_NQueen/BOJ_9663_G5_NQueen.java
  Hyeonmin/src/week32/BOJ_9663_G5_NQueen/readme.md
Labels: Backtracking

#350 HYEONMIN JO: BOJ 19236 G2 청소년 상어
  Hyeonmin/src/week32/BOJ_19236_G2_청소년상어/BOJ_19236_G2_청소년상어.java
  Hyeonmin/src/week32/BOJ_19236_G2_청소년상어/readme.md
Labels: Simulation, Backtracking

#351 HYEONMIN JO: BOJ 1956 G4 운동
  Hyeonmin/src/week32/BOJ_1956_G4_운동/BOJ_1956_G4_운동.java
  Hyeonmin/src/week32/BOJ_1956_G4_운동/readme.md
Labels: Floyd–Warshall

#354 HYEONMIN JO: BOJ 2610 G2 회의준비
  Hyeonmin/src/week32/BOJ_2610_G2_회의준비/BOJ_2610_G2_회의준비.java
  Hyeonmin/src/week32/BOJ_2610_G2_회의준비/readme.md
Labels: Floyd–Warshall
